services:
  api:
    image: gabrielmelogm/lumi-api:latest
    container_name: "lumi-api"
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      DATABASE_URL: "postgresql://docker:docker@database:5432/lumi"
      TRUSTED_DOMAINS: "*"
      PORT: "3000"
  
  database:
    image: postgres:16-alpine
    container_name: "lumi-database"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "lumi"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: