version: '3'

services:
  api:
    image: gabrielmelogm/lumi-api:latest
    container_name: "lumi-api"
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`lumi-api.gabrielmelo.cloud`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=leresolver"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TRUSTED_DOMAINS: ${TRUSTED_DOMAINS}
      PORT: ${PORT}
  
  database:
    image: postgres:16-alpine
    container_name: "lumi-database"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
