services:
  api:
    image: gabrielmelogm/lumi-api:latest
    container_name: "lumi-api"
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:lumi-api.gabrielmelo.cloud"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TRUSTED_DOMAINS: ${TRUSTED_DOMAINS}
      PORT: ${PORT}
  
  database:
    image: postgres:16-alpine
    container_name: "lumi-database"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data

  reverse-proxy:
    image: traefik
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db: