services:
  api:
    build: .
    container_name: "lumi-api"
    entrypoint: .docker/scripts/start_api.sh
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - database
    volumes:
      - .:/home/node/app
    environment:
      DATABASE_URL: "postgresql://docker:docker@database:5432/lumi"
      SHADOW_DATABASE_URL: "postgresql://docker:docker@shadow_database:5432/shadow_lumi"
      TRUSTED_DOMAINS: "*"
      PORT: "3000"

  web:
    build: .
    container_name: "lumi-web"
    entrypoint: .docker/scripts/start_web.sh
    ports:
      - "5173:5173"
    links:
      - api
    volumes:
      - .:/home/node/app
    environment:
      VITE_API_URL: "http://localhost:3000"
  
  database:
    image: postgres:16-alpine
    container_name: "lumi-database"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "lumi"
    volumes:
      - db:/var/lib/postgresql/data

  shadow_database:
    image: postgres:16-alpine
    container_name: "lumi-shadow_database"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "shadow_lumi"
    volumes:
      - shadow_db:/var/lib/postgresql/data

volumes:
  db:
  shadow_db: